cp/realestate/protected/controllers/InfoController.php
<?php

class InfoController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','output'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Info;
        
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);
       
		if(isset($_POST['Info']))
		{   
            //random number for image
            $random = rand(0,99);
            //date of uploading image
            $date = DATE('Y_M_d_h_i_s');
            
			$model->attributes=$_POST['Info'];
            
            $photo_comment = $model->Commentary_to_photo;
            //get instance of image
            $upload_image = CUploadedFile::getInstance($model,'image');
            //setting the image name
            $file_name = "{$random}_{$date}.".$upload_image->extensionName; 
            //saving image to the folder
            $upload_image->saveAs('uploads/big/'.$file_name);
            //add extension for resize
            Yii::import('application.extensions.EWideImage.EWideImage');
            //resize and save image with new name(adding 'small' to the name)
            EWideImage::load('uploads/big/'.$file_name)->resize(140, 140)->saveToFile('uploads/small/'.'small_'.$file_name);
            //create new object of Photo
            $newPhoto = new Photo();
            //add to db the photo name which user gave
            $newPhoto->photo_name = $file_name;
            //add to db url of the big photo
            $newPhoto->big = 'uploads/big/'.$file_name;
            //add to db url of the small photo
            $newPhoto->small = 'uploads/small/'.'small_'.$file_name;
            //add to db commentary to the photo if user gave it
            $newPhoto->commentary = $photo_comment;
            //saving the data to db
            $newPhoto->save();
            //saving to table Info ID of the photo
            $model->ID_photo = $newPhoto->ID_photo;
            
			if($model->save()){
                $model->after();
				$this->redirect(array('view','id'=>$model->ID_info));
                
                
            }
        }

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Info']))
		{
			$model->attributes=$_POST['Info'];
         
			if($model->save())
				$this->redirect(array('view','id'=>$model->ID_info));
                
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Info');
        $data = $dataProvider->getData();
        $this->render('index',array(
            'dataProvider'=>$dataProvider,
            'data'=>$data,
        ));
	}
    
        public function actionOutput()
    {
        $dataProvider=new CActiveDataProvider('Info');
        $data = $dataProvider->getData();
        $this->render('output',array(
            'dataProvider'=>$dataProvider,
            'data'=>$data,
        ));
    }

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Info('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Info']))
			$model->attributes=$_GET['Info'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Info::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='info-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

cp/realestate/protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
		// renders the view file 'protected/views/site/index.php'
		// using the default layout 'protected/views/layouts/main.php'
		$this->render('index');
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}


    public function actionSearch()
    {
        $searchForm = new SearchForm();
        $infoModel = new Info();
        $dataProvider = '';

        if (isset($_POST['SearchForm'])) {
            $searchForm->attributes = $_POST['SearchForm'];


                $parsed = array();
                $parsed = $searchForm->parse($searchForm->searchString);

                $criteria = new CDbCriteria();

                if (isset($parsed[0]) && isset($parsed[1]) && isset($parsed[2])) {
//                    $searchResults = Info::model()->findAllByAttributes(array(
//                        'ID_offer' => $parsed[0],
//                        'ID_info' => $parsed[1],
//                        'ID_coast' => $parsed[2]
//                    ));

                    $criteria->condition = "ID_offer = :p1 AND ID_info = :p2 AND ID_coast = :p3";
                    $criteria->params = array(':p1' => $parsed[0], 'p2' => $parsed[1], 'p3' => $parsed[2]);

                } else if(isset($parsed[0]) && isset($parsed[1])) {
//                    $searchResults = Info::model()->findAllByAttributes(array(
//                        'ID_offer' => $parsed[0],
//                        'ID_info' => $parsed[1]
//                    ));
                    $criteria->condition = "ID_offer = :p1 AND ID_info = :p2";
                    $criteria->params = array(':p1' => $parsed[0], 'p2' => $parsed[1]);
                } 

                $dataProvider = new CActiveDataProvider('Info', array(
                    'criteria' => $criteria,
                ));

        }

        $this->render('search', array(
            'model' => $searchForm,
            'infoModel' => $infoModel,
            'dataProvider' => $dataProvider,
        ));

    }

	/**
	 * Displays the contact page
	 */
	public function actionContact()
	{
		$model=new ContactForm;
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
				$name='=?UTF-8?B?'.base64_encode($model->name).'?=';
				$subject='=?UTF-8?B?'.base64_encode($model->subject).'?=';
				$headers="From: $name <{$model->email}>\r\n".
					"Reply-To: {$model->email}\r\n".
					"MIME-Version: 1.0\r\n".
					"Content-type: text/plain; charset=UTF-8";

				mail(Yii::app()->params['adminEmail'],$subject,$model->body,$headers);
				Yii::app()->user->setFlash('contact','Thank you for contacting us. We will respond to you as soon as possible.');
				$this->refresh();
			}
		}
		$this->render('contact',array('model'=>$model));
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login())
				$this->redirect(Yii::app()->user->returnUrl);
		}
		// display the login form
		$this->render('login',array('model'=>$model));
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}
}

cp/realestate/protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

cp/realestate/protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="row">
    <div class="span9">
        <div id="content">
            <?php echo $content; ?>
        </div><!-- content -->
    </div>
    <div class="span3">
        <div id="sidebar">
        <?php
            $this->beginWidget('zii.widgets.CPortlet', array(
                'title'=>'Operations',
            ));
            $this->widget('bootstrap.widgets.TbMenu', array(
                'items'=>$this->menu,
                'htmlOptions'=>array('class'=>'operations'),
            ));
            $this->endWidget();
        ?>
        </div><!-- sidebar -->
    </div>
</div>
<?php $this->endContent(); ?>

cp/realestate/protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="language" content="en" />

    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->baseUrl; ?>/css/main.css" />


    <title><?php echo CHtml::encode($this->pageTitle); ?></title>

    <?php Yii::app()->bootstrap->register(); 
    Yii::import('application.extensions.EWideImage.EWideImage'); 
    ?>
</head>

<body>

<?php $this->widget('bootstrap.widgets.TbNavbar',array(
    'items'=>array(
        array(
            'class'=>'bootstrap.widgets.TbMenu',
            'items'=>array(
                array('label'=>'Главная', 'url'=>array('/site/index')),
                array('label'=>'Отзывы', 'url'=>array('/site/page', 'view'=>'about')),
                array('label'=>'Обратная связь', 'url'=>array('/site/contact')),
                array('label'=>'Поиск', 'url'=>array('/site/search')),
                array('label'=>'Предварительный вывод', 'url'=>array('/info/index')),
                array('label'=>'Войти', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
                array('label'=>'Выйти ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
            ),
        ),
    ),
)); ?>

<div class="container" id="page">

    <?php if(isset($this->breadcrumbs)):?>
        <?php $this->widget('bootstrap.widgets.TbBreadcrumbs', array(
            'links'=>$this->breadcrumbs,
        )); ?><!-- breadcrumbs -->
    <?php endif?>

    <?php echo $content; ?>

    <div class="clear"></div>

    <div id="footer">
        Практика студентов выпускников Академии Смарт (группа 13, 14) &copy; <?php echo date('Y'); ?> .<br/>
        
        
    </div><!-- footer -->

</div><!-- page -->

</body>
</html>